# Generated by Django 2.0.5 on 2018-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Super Administrador'),
        ),
    ]
