# Generated by Django 2.0.5 on 2018-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20181213_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Super Administrador'),
        ),
    ]
