# Generated by Django 2.0.5 on 2018-12-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiapp', '0002_auto_20181213_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cupos',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
