# Generated by Django 2.0.5 on 2019-01-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiapp', '0003_curso_cupos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='cupos',
            new_name='cupos_restantes',
        ),
        migrations.AddField(
            model_name='curso',
            name='total_cupos',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
